USE codeup_test_db;


INSERT INTO albums (id, artist, record_name, sales, genre)
VALUES
(1, 'Michael Jackson', 'Thriller', 47.3, 'Pop'),
(2, 'Eagles', 'Their Greatest Hits (1971-1975)', 41.2, 'Country rock'),
(3, 'AC/DC', 'Back in Black', 26.1, 'Hard rock'),
(4, 'Pink Floyd', 'The Dark Side of the Moon', 24.2, 'Progressive rock'),
(5, 'Whitney Houston', 'The Bodyguard', 28.4, 'R&B'),
(6, 'Meat Loaf', 'Bat Out of Hell', 21.5, 'Hard rock'),
(7, 'Eagles', 'Hotel California', 31.5, 'Soft rock'),
(8, 'Bee Gees', 'Saturday Night Fever', 21.6, 'Disco'),
(9, 'Fleetwood Mac', 'Rumours', 27.9, 'Soft rock'),
(10, 'Shania Twain', 'Come On Over', 29.6, 'Country'),
(11, 'Led Zeppelin', 'Led Zeppelin IV', 29.0, 'Hard rock'),
(12, 'Micheal Jackson', 'Bad', 19.3, 'Pop'),
(13, 'Alanis Morissette', 'Jagged Little Pill', 24.4, 'Alternative rock'),
(14, 'Celine Dion', 'Falling into You', 20.2, 'Pop'),
(15, 'The Beatles', 'Sgt Peppers Lonely Hearts Club Band', 18.2, 'Rock' ),
(16, 'Michael Jackson', 'Dangerous', 17.3, 'Rock'),
(17, 'Adele', '21', 25.3, 'Pop'),
(18, 'Celine Dion', 'Lets Talk About Love', 19.3, 'Pop'),
(19, 'The Beatles', '1', 23.4, 'Rock'),
(20, 'ABBA', 'Gold: Greatest Hits', 23.0, 'Pop'),
(21, 'Madonna', 'The Immaculate Collection', 19.4, 'Pop'),
(22, 'The Beatles', 'Abbey Road', 14.4, 'Rock'),
(23, 'Bruce Springsteen', 'Born in the U.S.A', 19.6, 'Heartland rock'),
(24, 'Dire Straits', 'Brothers in Arms', 17.7, 'Roots rock'),
(25, 'James Horner', 'Titanic: Music from the Motion Picture', 18.1, 'Film score'),
(26, 'Metallica', 'Metallica', 25.2, 'Heavy Metal'),
(27, 'Nirvana', 'Nevermind', 16.7, 'Grunge'),
(28, 'Pink Floyd', 'The Wall', 18.7, 'Progressive rock'),
(29, 'Santana', 'Supernatural', 20.5, 'Latin rock'),
(30, 'Guns N Roses', 'Appetite for Destruction', 21.6, 'Hard rock' ))
