USE codeup_test_db;
DROP TABLE IF EXISTS albums;

CREATE TABLE IF NOT EXISTS albums (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    artist VARCHAR(50) NOT NULL,
    record_name VARCHAR(100) NOT NULL,
    sales DECIMAL(10, 2) NOT NULL,
    genre VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);
